const NAICSCode = [
    {
        sequenceNo: 3,
        shortCode: '11',
        NAICSGroup: 'Agriculture, Forestry, Fishing and Hunting',
        code: '1111',
        title: 'Oilseed and Grain Farming',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 19,
        shortCode: '11',
        NAICSGroup: 'Agriculture, Forestry, Fishing and Hunting',
        code: '1112',
        title: 'Vegetable and Melon Farming',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 23,
        shortCode: '11',
        NAICSGroup: 'Agriculture, Forestry, Fishing and Hunting',
        code: '1113',
        title: 'Fruit and Tree Nut Farming',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 36,
        shortCode: '11',
        NAICSGroup: 'Agriculture, Forestry, Fishing and Hunting',
        code: '1114',
        title: 'Greenhouse, Nursery, and Floriculture Production',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 43,
        shortCode: '11',
        NAICSGroup: 'Agriculture, Forestry, Fishing and Hunting',
        code: '1119',
        title: 'Other Crop Farming',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 57,
        shortCode: '11',
        NAICSGroup: 'Agriculture, Forestry, Fishing and Hunting',
        code: '1121',
        title: 'Cattle Ranching and Farming',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 65,
        shortCode: '11',
        NAICSGroup: 'Agriculture, Forestry, Fishing and Hunting',
        code: '1122',
        title: 'Hog and Pig Farming',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 68,
        shortCode: '11',
        NAICSGroup: 'Agriculture, Forestry, Fishing and Hunting',
        code: '1123',
        title: 'Poultry and Egg Production',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 79,
        shortCode: '11',
        NAICSGroup: 'Agriculture, Forestry, Fishing and Hunting',
        code: '1124',
        title: 'Sheep and Goat Farming',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 84,
        shortCode: '11',
        NAICSGroup: 'Agriculture, Forestry, Fishing and Hunting',
        code: '1125',
        title: 'Aquaculture',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 89,
        shortCode: '11',
        NAICSGroup: 'Agriculture, Forestry, Fishing and Hunting',
        code: '1129',
        title: 'Other Animal Production',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 99,
        shortCode: '11',
        NAICSGroup: 'Agriculture, Forestry, Fishing and Hunting',
        code: '1131',
        title: 'Timber Tract Operations',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 102,
        shortCode: '11',
        NAICSGroup: 'Agriculture, Forestry, Fishing and Hunting',
        code: '1132',
        title: 'Forest Nurseries and Gathering of Forest Products',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 105,
        shortCode: '11',
        NAICSGroup: 'Agriculture, Forestry, Fishing and Hunting',
        code: '1133',
        title: 'Logging',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 109,
        shortCode: '11',
        NAICSGroup: 'Agriculture, Forestry, Fishing and Hunting',
        code: '1141',
        title: 'Fishing',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 114,
        shortCode: '11',
        NAICSGroup: 'Agriculture, Forestry, Fishing and Hunting',
        code: '1142',
        title: 'Hunting and Trapping',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 118,
        shortCode: '11',
        NAICSGroup: 'Agriculture, Forestry, Fishing and Hunting',
        code: '1151',
        title: 'Support Activities for Crop Production',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 126,
        shortCode: '11',
        NAICSGroup: 'Agriculture, Forestry, Fishing and Hunting',
        code: '1152',
        title: 'Support Activities for Animal Production',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 129,
        shortCode: '11',
        NAICSGroup: 'Agriculture, Forestry, Fishing and Hunting',
        code: '1153',
        title: 'Support Activities for Forestry',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 134,
        shortCode: '21',
        NAICSGroup: 'Mining, Quarrying, and Oil and Gas Extraction',
        code: '2111',
        title: 'Oil and Gas Extraction',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 140,
        shortCode: '21',
        NAICSGroup: 'Mining, Quarrying, and Oil and Gas Extraction',
        code: '2121',
        title: 'Coal Mining',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 145,
        shortCode: '21',
        NAICSGroup: 'Mining, Quarrying, and Oil and Gas Extraction',
        code: '2122',
        title: 'Metal Ore Mining',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 156,
        shortCode: '21',
        NAICSGroup: 'Mining, Quarrying, and Oil and Gas Extraction',
        code: '2123',
        title: 'Nonmetallic Mineral Mining and Quarrying',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 173,
        shortCode: '21',
        NAICSGroup: 'Mining, Quarrying, and Oil and Gas Extraction',
        code: '2131',
        title: 'Support Activities for Mining',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 182,
        shortCode: '22',
        NAICSGroup: 'Utilities',
        code: '2211',
        title: 'Electric Power Generation, Transmission and Distribution',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 195,
        shortCode: '22',
        NAICSGroup: 'Utilities',
        code: '2212',
        title: 'Natural Gas Distribution ',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 198,
        shortCode: '22',
        NAICSGroup: 'Utilities',
        code: '2213',
        title: 'Water, Sewage and Other Systems ',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 207,
        shortCode: '23',
        NAICSGroup: 'Construction',
        code: '2361',
        title: 'Residential Building Construction',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 213,
        shortCode: '23',
        NAICSGroup: 'Construction',
        code: '2362',
        title: 'Nonresidential Building Construction',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 219,
        shortCode: '23',
        NAICSGroup: 'Construction',
        code: '2371',
        title: 'Utility System Construction',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 226,
        shortCode: '23',
        NAICSGroup: 'Construction',
        code: '2372',
        title: 'Land Subdivision',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 229,
        shortCode: '23',
        NAICSGroup: 'Construction',
        code: '2373',
        title: 'Highway, Street, and Bridge Construction',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 232,
        shortCode: '23',
        NAICSGroup: 'Construction',
        code: '2379',
        title: 'Other Heavy and Civil Engineering Construction',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 236,
        shortCode: '23',
        NAICSGroup: 'Construction',
        code: '2381',
        title: 'Foundation, Structure, and Building Exterior Contractors',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 253,
        shortCode: '23',
        NAICSGroup: 'Construction',
        code: '2382',
        title: 'Building Equipment Contractors',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 260,
        shortCode: '23',
        NAICSGroup: 'Construction',
        code: '2383',
        title: 'Building Finishing Contractors',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 273,
        shortCode: '23',
        NAICSGroup: 'Construction',
        code: '2389',
        title: 'Other Specialty Trade Contractors',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 280,
        shortCode: '31',
        NAICSGroup: 'Manufacturing',
        code: '3111',
        title: 'Animal Food Manufacturing',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 284,
        shortCode: '31',
        NAICSGroup: 'Manufacturing',
        code: '3112',
        title: 'Grain and Oilseed Milling',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 295,
        shortCode: '31',
        NAICSGroup: 'Manufacturing',
        code: '3113',
        title: 'Sugar and Confectionery Product Manufacturing',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 304,
        shortCode: '31',
        NAICSGroup: 'Manufacturing',
        code: '3114',
        title: 'Fruit and Vegetable Preserving and Specialty Food Manufacturing',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 312,
        shortCode: '31',
        NAICSGroup: 'Manufacturing',
        code: '3115',
        title: 'Dairy Product Manufacturing',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 320,
        shortCode: '31',
        NAICSGroup: 'Manufacturing',
        code: '3116',
        title: 'Animal Slaughtering and Processing',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 326,
        shortCode: '31',
        NAICSGroup: 'Manufacturing',
        code: '3117',
        title: 'Seafood Product Preparation and Packaging',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 329,
        shortCode: '31',
        NAICSGroup: 'Manufacturing',
        code: '3118',
        title: 'Bakeries and Tortilla Manufacturing',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 339,
        shortCode: '31',
        NAICSGroup: 'Manufacturing',
        code: '3119',
        title: 'Other Food Manufacturing',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 354,
        shortCode: '31',
        NAICSGroup: 'Manufacturing',
        code: '3121',
        title: 'Beverage Manufacturing',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 365,
        shortCode: '31',
        NAICSGroup: 'Manufacturing',
        code: '3122',
        title: 'Tobacco Manufacturing',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 369,
        shortCode: '31',
        NAICSGroup: 'Manufacturing',
        code: '3131',
        title: 'Fiber, Yarn, and Thread Mills',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 372,
        shortCode: '31',
        NAICSGroup: 'Manufacturing',
        code: '3132',
        title: 'Fabric Mills',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 381,
        shortCode: '31',
        NAICSGroup: 'Manufacturing',
        code: '3133',
        title: 'Textile and Fabric Finishing and Fabric Coating Mills',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 387,
        shortCode: '31',
        NAICSGroup: 'Manufacturing',
        code: '3141',
        title: 'Textile Furnishings Mills',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 392,
        shortCode: '31',
        NAICSGroup: 'Manufacturing',
        code: '3149',
        title: 'Other Textile Product Mills',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 399,
        shortCode: '31',
        NAICSGroup: 'Manufacturing',
        code: '3151',
        title: 'Apparel Knitting Mills',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 404,
        shortCode: '31',
        NAICSGroup: 'Manufacturing',
        code: '3152',
        title: 'Cut and Sew Apparel Manufacturing',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 413,
        shortCode: '31',
        NAICSGroup: 'Manufacturing',
        code: '3159',
        title: 'Apparel Accessories and Other Apparel Manufacturing',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 417,
        shortCode: '31',
        NAICSGroup: 'Manufacturing',
        code: '3161',
        title: 'Leather and Hide Tanning and Finishing',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 420,
        shortCode: '31',
        NAICSGroup: 'Manufacturing',
        code: '3162',
        title: 'Footwear Manufacturing',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 423,
        shortCode: '31',
        NAICSGroup: 'Manufacturing',
        code: '3169',
        title: 'Other Leather and Allied Product Manufacturing',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 428,
        shortCode: '32',
        NAICSGroup: 'Manufacturing',
        code: '3211',
        title: 'Sawmills and Wood Preservation',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 432,
        shortCode: '32',
        NAICSGroup: 'Manufacturing',
        code: '3212',
        title: 'Veneer, Plywood, and Engineered Wood Product Manufacturing',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 439,
        shortCode: '32',
        NAICSGroup: 'Manufacturing',
        code: '3219',
        title: 'Other Wood Product Manufacturing',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 451,
        shortCode: '32',
        NAICSGroup: 'Manufacturing',
        code: '3221',
        title: 'Pulp, Paper, and Paperboard Mills',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 459,
        shortCode: '32',
        NAICSGroup: 'Manufacturing',
        code: '3222',
        title: 'Converted Paper Product Manufacturing',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 472,
        shortCode: '32',
        NAICSGroup: 'Manufacturing',
        code: '3231',
        title: 'Printing and Related Support Activities',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 480,
        shortCode: '32',
        NAICSGroup: 'Manufacturing',
        code: '3241',
        title: 'Petroleum and Coal Products Manufacturing',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 490,
        shortCode: '32',
        NAICSGroup: 'Manufacturing',
        code: '3251',
        title: 'Basic Chemical Manufacturing',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 503,
        shortCode: '32',
        NAICSGroup: 'Manufacturing',
        code: '3252',
        title: 'Resin, Synthetic Rubber, and Artificial and Synthetic Fibers and Filaments Manufacturing',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 509,
        shortCode: '32',
        NAICSGroup: 'Manufacturing',
        code: '3253',
        title: 'Pesticide, Fertilizer, and Other Agricultural Chemical Manufacturing',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 516,
        shortCode: '32',
        NAICSGroup: 'Manufacturing',
        code: '3254',
        title: 'Pharmaceutical and Medicine Manufacturing',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 522,
        shortCode: '32',
        NAICSGroup: 'Manufacturing',
        code: '3255',
        title: 'Paint, Coating, and Adhesive Manufacturing',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 527,
        shortCode: '32',
        NAICSGroup: 'Manufacturing',
        code: '3256',
        title: 'Soap, Cleaning Compound, and Toilet Preparation Manufacturing',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 534,
        shortCode: '32',
        NAICSGroup: 'Manufacturing',
        code: '3259',
        title: 'Other Chemical Product and Preparation Manufacturing',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 544,
        shortCode: '32',
        NAICSGroup: 'Manufacturing',
        code: '3261',
        title: 'Plastics Product Manufacturing',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 563,
        shortCode: '32',
        NAICSGroup: 'Manufacturing',
        code: '3262',
        title: 'Rubber Product Manufacturing',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 573,
        shortCode: '32',
        NAICSGroup: 'Manufacturing',
        code: '3271',
        title: 'Clay Product and Refractory Manufacturing',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 578,
        shortCode: '32',
        NAICSGroup: 'Manufacturing',
        code: '3272',
        title: 'Glass and Glass Product Manufacturing',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 584,
        shortCode: '32',
        NAICSGroup: 'Manufacturing',
        code: '3273',
        title: 'Cement and Concrete Product Manufacturing',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 594,
        shortCode: '32',
        NAICSGroup: 'Manufacturing',
        code: '3274',
        title: 'Lime and Gypsum Product Manufacturing',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 599,
        shortCode: '32',
        NAICSGroup: 'Manufacturing',
        code: '3279',
        title: 'Other Nonmetallic Mineral Product Manufacturing',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 608,
        shortCode: '33',
        NAICSGroup: 'Manufacturing',
        code: '3311',
        title: 'Iron and Steel Mills and Ferroalloy Manufacturing',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 611,
        shortCode: '33',
        NAICSGroup: 'Manufacturing',
        code: '3312',
        title: 'Steel Product Manufacturing from Purchased Steel',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 617,
        shortCode: '33',
        NAICSGroup: 'Manufacturing',
        code: '3313',
        title: 'Alumina and Aluminum Production and Processing',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 623,
        shortCode: '33',
        NAICSGroup: 'Manufacturing',
        code: '3314',
        title: 'Nonferrous Metal (except Aluminum) Production and Processing',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 631,
        shortCode: '33',
        NAICSGroup: 'Manufacturing',
        code: '3315',
        title: 'Foundries',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 641,
        shortCode: '33',
        NAICSGroup: 'Manufacturing',
        code: '3321',
        title: 'Forging and Stamping',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 648,
        shortCode: '33',
        NAICSGroup: 'Manufacturing',
        code: '3322',
        title: 'Cutlery and Handtool Manufacturing',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 652,
        shortCode: '33',
        NAICSGroup: 'Manufacturing',
        code: '3323',
        title: 'Architectural and Structural Metals Manufacturing',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 661,
        shortCode: '33',
        NAICSGroup: 'Manufacturing',
        code: '3324',
        title: 'Boiler, Tank, and Shipping Container Manufacturing',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 669,
        shortCode: '33',
        NAICSGroup: 'Manufacturing',
        code: '3325',
        title: 'Hardware Manufacturing',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 672,
        shortCode: '33',
        NAICSGroup: 'Manufacturing',
        code: '3326',
        title: 'Spring and Wire Product Manufacturing',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 676,
        shortCode: '33',
        NAICSGroup: 'Manufacturing',
        code: '3327',
        title: 'Machine Shops; Turned Product; and Screw, Nut, and Bolt Manufacturing',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 682,
        shortCode: '33',
        NAICSGroup: 'Manufacturing',
        code: '3328',
        title: 'Coating, Engraving, Heat Treating, and Allied Activities',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 687,
        shortCode: '33',
        NAICSGroup: 'Manufacturing',
        code: '3329',
        title: 'Other Fabricated Metal Product Manufacturing',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 701,
        shortCode: '33',
        NAICSGroup: 'Manufacturing',
        code: '3331',
        title: 'Agriculture, Construction, and Mining Machinery Manufacturing',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 710,
        shortCode: '33',
        NAICSGroup: 'Manufacturing',
        code: '3332',
        title: 'Industrial Machinery Manufacturing',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 717,
        shortCode: '33',
        NAICSGroup: 'Manufacturing',
        code: '3333',
        title: 'Commercial and Service Industry Machinery Manufacturing',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 722,
        shortCode: '33',
        NAICSGroup: 'Manufacturing',
        code: '3334',
        title: 'Ventilation, Heating, Air-Conditioning, and Commercial Refrigeration Equipment Manufacturing',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 727,
        shortCode: '33',
        NAICSGroup: 'Manufacturing',
        code: '3335',
        title: 'Metalworking Machinery Manufacturing',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 734,
        shortCode: '33',
        NAICSGroup: 'Manufacturing',
        code: '3336',
        title: 'Engine, Turbine, and Power Transmission Equipment Manufacturing',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 740,
        shortCode: '33',
        NAICSGroup: 'Manufacturing',
        code: '3339',
        title: 'Other General Purpose Machinery Manufacturing',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 759,
        shortCode: '33',
        NAICSGroup: 'Manufacturing',
        code: '3341',
        title: 'Computer and Peripheral Equipment Manufacturing',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 764,
        shortCode: '33',
        NAICSGroup: 'Manufacturing',
        code: '3342',
        title: 'Communications Equipment Manufacturing',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 771,
        shortCode: '33',
        NAICSGroup: 'Manufacturing',
        code: '3343',
        title: 'Audio and Video Equipment Manufacturing',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 774,
        shortCode: '33',
        NAICSGroup: 'Manufacturing',
        code: '3344',
        title: 'Semiconductor and Other Electronic Component Manufacturing',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 782,
        shortCode: '33',
        NAICSGroup: 'Manufacturing',
        code: '3345',
        title: 'Navigational, Measuring, Electromedical, and Control Instruments Manufacturing',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 793,
        shortCode: '33',
        NAICSGroup: 'Manufacturing',
        code: '3346',
        title: 'Manufacturing and Reproducing Magnetic and Optical Media',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 798,
        shortCode: '33',
        NAICSGroup: 'Manufacturing',
        code: '3351',
        title: 'Electric Lighting Equipment Manufacturing',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 805,
        shortCode: '33',
        NAICSGroup: 'Manufacturing',
        code: '3352',
        title: 'Household Appliance Manufacturing',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 810,
        shortCode: '33',
        NAICSGroup: 'Manufacturing',
        code: '3353',
        title: 'Electrical Equipment Manufacturing',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 816,
        shortCode: '33',
        NAICSGroup: 'Manufacturing',
        code: '3359',
        title: 'Other Electrical Equipment and Component Manufacturing',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 830,
        shortCode: '33',
        NAICSGroup: 'Manufacturing',
        code: '3361',
        title: 'Motor Vehicle Manufacturing',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 836,
        shortCode: '33',
        NAICSGroup: 'Manufacturing',
        code: '3362',
        title: 'Motor Vehicle Body and Trailer Manufacturing',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 842,
        shortCode: '33',
        NAICSGroup: 'Manufacturing',
        code: '3363',
        title: 'Motor Vehicle Parts Manufacturing',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 859,
        shortCode: '33',
        NAICSGroup: 'Manufacturing',
        code: '3364',
        title: 'Aerospace Product and Parts Manufacturing',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 867,
        shortCode: '33',
        NAICSGroup: 'Manufacturing',
        code: '3365',
        title: 'Railroad Rolling Stock Manufacturing',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 870,
        shortCode: '33',
        NAICSGroup: 'Manufacturing',
        code: '3366',
        title: 'Ship and Boat Building',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 874,
        shortCode: '33',
        NAICSGroup: 'Manufacturing',
        code: '3369',
        title: 'Other Transportation Equipment Manufacturing',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 880,
        shortCode: '33',
        NAICSGroup: 'Manufacturing',
        code: '3371',
        title: 'Household and Institutional Furniture and Kitchen Cabinet Manufacturing',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 889,
        shortCode: '33',
        NAICSGroup: 'Manufacturing',
        code: '3372',
        title: 'Office Furniture (including Fixtures) Manufacturing',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 895,
        shortCode: '33',
        NAICSGroup: 'Manufacturing',
        code: '3379',
        title: 'Other Furniture Related Product Manufacturing',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 901,
        shortCode: '33',
        NAICSGroup: 'Manufacturing',
        code: '3391',
        title: 'Medical Equipment and Supplies Manufacturing',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 908,
        shortCode: '33',
        NAICSGroup: 'Manufacturing',
        code: '3399',
        title: 'Other Miscellaneous Manufacturing',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 928,
        shortCode: '42',
        NAICSGroup: 'Wholesale Trade',
        code: '4231',
        title: 'Motor Vehicle and Motor Vehicle Parts and Supplies Merchant Wholesalers ',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 937,
        shortCode: '42',
        NAICSGroup: 'Wholesale Trade',
        code: '4232',
        title: 'Furniture and Home Furnishing Merchant Wholesalers ',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 942,
        shortCode: '42',
        NAICSGroup: 'Wholesale Trade',
        code: '4233',
        title: 'Lumber and Other Construction Materials Merchant Wholesalers ',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 951,
        shortCode: '42',
        NAICSGroup: 'Wholesale Trade',
        code: '4234',
        title: 'Professional and Commercial Equipment and Supplies Merchant Wholesalers ',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 966,
        shortCode: '42',
        NAICSGroup: 'Wholesale Trade',
        code: '4235',
        title: 'Metal and Mineral (except Petroleum) Merchant Wholesalers ',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 971,
        shortCode: '42',
        NAICSGroup: 'Wholesale Trade',
        code: '4236',
        title: 'Household Appliances and Electrical and Electronic Goods Merchant Wholesalers ',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 978,
        shortCode: '42',
        NAICSGroup: 'Wholesale Trade',
        code: '4237',
        title: 'Hardware, and Plumbing and Heating Equipment and Supplies Merchant Wholesalers ',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 987,
        shortCode: '42',
        NAICSGroup: 'Wholesale Trade',
        code: '4238',
        title: 'Machinery, Equipment, and Supplies Merchant Wholesalers ',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 1000,
        shortCode: '42',
        NAICSGroup: 'Wholesale Trade',
        code: '4239',
        title: 'Miscellaneous Durable Goods Merchant Wholesalers ',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 1012,
        shortCode: '42',
        NAICSGroup: 'Wholesale Trade',
        code: '4241',
        title: 'Paper and Paper Product Merchant Wholesalers ',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 1019,
        shortCode: '42',
        NAICSGroup: 'Wholesale Trade',
        code: '4242',
        title: "Drugs and Druggists' Sundries Merchant Wholesalers ",
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 1022,
        shortCode: '42',
        NAICSGroup: 'Wholesale Trade',
        code: '4243',
        title: 'Apparel, Piece Goods, and Notions Merchant Wholesalers ',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 1031,
        shortCode: '42',
        NAICSGroup: 'Wholesale Trade',
        code: '4244',
        title: 'Grocery and Related Product Merchant Wholesalers ',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 1050,
        shortCode: '42',
        NAICSGroup: 'Wholesale Trade',
        code: '4245',
        title: 'Farm Product Raw Material Merchant Wholesalers ',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 1057,
        shortCode: '42',
        NAICSGroup: 'Wholesale Trade',
        code: '4246',
        title: 'Chemical and Allied Products Merchant Wholesalers ',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 1062,
        shortCode: '42',
        NAICSGroup: 'Wholesale Trade',
        code: '4247',
        title: 'Petroleum and Petroleum Products Merchant Wholesalers ',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 1067,
        shortCode: '42',
        NAICSGroup: 'Wholesale Trade',
        code: '4248',
        title: 'Beer, Wine, and Distilled Alcoholic Beverage Merchant Wholesalers ',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 1072,
        shortCode: '42',
        NAICSGroup: 'Wholesale Trade',
        code: '4249',
        title: 'Miscellaneous Nondurable Goods Merchant Wholesalers ',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 1086,
        shortCode: '42',
        NAICSGroup: 'Wholesale Trade',
        code: '4251',
        title: 'Wholesale Electronic Markets and Agents and Brokers ',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 1093,
        shortCode: '44',
        NAICSGroup: 'Retail Trade',
        code: '4411',
        title: 'Automobile Dealers ',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 1098,
        shortCode: '44',
        NAICSGroup: 'Retail Trade',
        code: '4412',
        title: 'Other Motor Vehicle Dealers ',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 1104,
        shortCode: '44',
        NAICSGroup: 'Retail Trade',
        code: '4413',
        title: 'Automotive Parts, Accessories, and Tire Stores ',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 1110,
        shortCode: '44',
        NAICSGroup: 'Retail Trade',
        code: '4421',
        title: 'Furniture Stores ',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 1113,
        shortCode: '44',
        NAICSGroup: 'Retail Trade',
        code: '4422',
        title: 'Home Furnishings Stores ',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 1120,
        shortCode: '44',
        NAICSGroup: 'Retail Trade',
        code: '4431',
        title: 'Electronics and Appliance Stores ',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 1125,
        shortCode: '44',
        NAICSGroup: 'Retail Trade',
        code: '4441',
        title: 'Building Material and Supplies Dealers ',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 1134,
        shortCode: '44',
        NAICSGroup: 'Retail Trade',
        code: '4442',
        title: 'Lawn and Garden Equipment and Supplies Stores ',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 1140,
        shortCode: '44',
        NAICSGroup: 'Retail Trade',
        code: '4451',
        title: 'Grocery Stores ',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 1145,
        shortCode: '44',
        NAICSGroup: 'Retail Trade',
        code: '4452',
        title: 'Specialty Food Stores ',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 1156,
        shortCode: '44',
        NAICSGroup: 'Retail Trade',
        code: '4453',
        title: 'Beer, Wine, and Liquor Stores ',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 1160,
        shortCode: '44',
        NAICSGroup: 'Retail Trade',
        code: '4461',
        title: 'Health and Personal Care Stores ',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 1171,
        shortCode: '44',
        NAICSGroup: 'Retail Trade',
        code: '4471',
        title: 'Gasoline Stations ',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 1177,
        shortCode: '44',
        NAICSGroup: 'Retail Trade',
        code: '4481',
        title: 'Clothing Stores ',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 1190,
        shortCode: '44',
        NAICSGroup: 'Retail Trade',
        code: '4482',
        title: 'Shoe Stores ',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 1193,
        shortCode: '44',
        NAICSGroup: 'Retail Trade',
        code: '4483',
        title: 'Jewelry, Luggage, and Leather Goods Stores ',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 1199,
        shortCode: '44',
        NAICSGroup: 'Retail Trade',
        code: '4511',
        title: 'Sporting Goods, Hobby, and Musical Instrument Stores ',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 1208,
        shortCode: '45',
        NAICSGroup: 'Retail Trade',
        code: '4512',
        title: 'Book Stores and News Dealers ',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 1213,
        shortCode: '45',
        NAICSGroup: 'Retail Trade',
        code: '4522',
        title: 'Department Stores ',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 1216,
        shortCode: '45',
        NAICSGroup: 'Retail Trade',
        code: '4523',
        title: 'General Merchandise Stores, including Warehouse Clubs and Supercenters ',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 1221,
        shortCode: '45',
        NAICSGroup: 'Retail Trade',
        code: '4531',
        title: 'Florists ',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 1224,
        shortCode: '45',
        NAICSGroup: 'Retail Trade',
        code: '4532',
        title: 'Office Supplies, Stationery, and Gift Stores ',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 1229,
        shortCode: '45',
        NAICSGroup: 'Retail Trade',
        code: '4533',
        title: 'Used Merchandise Stores ',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 1232,
        shortCode: '45',
        NAICSGroup: 'Retail Trade',
        code: '4539',
        title: 'Other Miscellaneous Store Retailers ',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 1243,
        shortCode: '45',
        NAICSGroup: 'Retail Trade',
        code: '4541',
        title: 'Electronic Shopping and Mail-Order Houses ',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 1246,
        shortCode: '45',
        NAICSGroup: 'Retail Trade',
        code: '4542',
        title: 'Vending Machine Operators ',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 1249,
        shortCode: '45',
        NAICSGroup: 'Retail Trade',
        code: '4543',
        title: 'Direct Selling Establishments ',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 1256,
        shortCode: '48',
        NAICSGroup: 'Transportation and Warehousing',
        code: '4811',
        title: 'Scheduled Air Transportation',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 1260,
        shortCode: '48',
        NAICSGroup: 'Transportation and Warehousing',
        code: '4812',
        title: 'Nonscheduled Air Transportation',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 1266,
        shortCode: '48',
        NAICSGroup: 'Transportation and Warehousing',
        code: '4821',
        title: 'Rail Transportation',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 1271,
        shortCode: '48',
        NAICSGroup: 'Transportation and Warehousing',
        code: '4831',
        title: 'Deep Sea, Coastal, and Great Lakes Water Transportation',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 1277,
        shortCode: '48',
        NAICSGroup: 'Transportation and Warehousing',
        code: '4832',
        title: 'Inland Water Transportation',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 1282,
        shortCode: '48',
        NAICSGroup: 'Transportation and Warehousing',
        code: '4841',
        title: 'General Freight Trucking',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 1288,
        shortCode: '48',
        NAICSGroup: 'Transportation and Warehousing',
        code: '4842',
        title: 'Specialized Freight Trucking',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 1296,
        shortCode: '48',
        NAICSGroup: 'Transportation and Warehousing',
        code: '4851',
        title: 'Urban Transit Systems',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 1302,
        shortCode: '48',
        NAICSGroup: 'Transportation and Warehousing',
        code: '4852',
        title: 'Interurban and Rural Bus Transportation',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 1305,
        shortCode: '48',
        NAICSGroup: 'Transportation and Warehousing',
        code: '4853',
        title: 'Taxi and Limousine Service',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 1310,
        shortCode: '48',
        NAICSGroup: 'Transportation and Warehousing',
        code: '4854',
        title: 'School and Employee Bus Transportation',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 1313,
        shortCode: '48',
        NAICSGroup: 'Transportation and Warehousing',
        code: '4855',
        title: 'Charter Bus Industry',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 1316,
        shortCode: '48',
        NAICSGroup: 'Transportation and Warehousing',
        code: '4859',
        title: 'Other Transit and Ground Passenger Transportation',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 1321,
        shortCode: '48',
        NAICSGroup: 'Transportation and Warehousing',
        code: '4861',
        title: 'Pipeline Transportation of Crude Oil',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 1324,
        shortCode: '48',
        NAICSGroup: 'Transportation and Warehousing',
        code: '4862',
        title: 'Pipeline Transportation of Natural Gas',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 1327,
        shortCode: '48',
        NAICSGroup: 'Transportation and Warehousing',
        code: '4869',
        title: 'Other Pipeline Transportation',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 1333,
        shortCode: '48',
        NAICSGroup: 'Transportation and Warehousing',
        code: '4871',
        title: 'Scenic and Sightseeing Transportation, Land',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 1336,
        shortCode: '48',
        NAICSGroup: 'Transportation and Warehousing',
        code: '4872',
        title: 'Scenic and Sightseeing Transportation, Water',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 1339,
        shortCode: '48',
        NAICSGroup: 'Transportation and Warehousing',
        code: '4879',
        title: 'Scenic and Sightseeing Transportation, Other',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 1343,
        shortCode: '48',
        NAICSGroup: 'Transportation and Warehousing',
        code: '4881',
        title: 'Support Activities for Air Transportation',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 1349,
        shortCode: '48',
        NAICSGroup: 'Transportation and Warehousing',
        code: '4882',
        title: 'Support Activities for Rail Transportation',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 1352,
        shortCode: '48',
        NAICSGroup: 'Transportation and Warehousing',
        code: '4883',
        title: 'Support Activities for Water Transportation',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 1361,
        shortCode: '48',
        NAICSGroup: 'Transportation and Warehousing',
        code: '4884',
        title: 'Support Activities for Road Transportation',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 1366,
        shortCode: '48',
        NAICSGroup: 'Transportation and Warehousing',
        code: '4885',
        title: 'Freight Transportation Arrangement',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 1369,
        shortCode: '48',
        NAICSGroup: 'Transportation and Warehousing',
        code: '4889',
        title: 'Other Support Activities for Transportation',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 1374,
        shortCode: '49',
        NAICSGroup: 'Transportation and Warehousing',
        code: '4911',
        title: 'Postal Service',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 1378,
        shortCode: '49',
        NAICSGroup: 'Transportation and Warehousing',
        code: '4921',
        title: 'Couriers and Express Delivery Services',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 1381,
        shortCode: '49',
        NAICSGroup: 'Transportation and Warehousing',
        code: '4922',
        title: 'Local Messengers and Local Delivery',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 1385,
        shortCode: '49',
        NAICSGroup: 'Transportation and Warehousing',
        code: '4931',
        title: 'Warehousing and Storage',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 1396,
        shortCode: '51',
        NAICSGroup: 'Information',
        code: '5111',
        title: 'Newspaper, Periodical, Book, and Directory Publishers',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 1408,
        shortCode: '51',
        NAICSGroup: 'Information',
        code: '5112',
        title: 'Software Publishers',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 1412,
        shortCode: '51',
        NAICSGroup: 'Information',
        code: '5121',
        title: 'Motion Picture and Video Industries',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 1423,
        shortCode: '51',
        NAICSGroup: 'Information',
        code: '5122',
        title: 'Sound Recording Industries',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 1433,
        shortCode: '51',
        NAICSGroup: 'Information',
        code: '5151',
        title: 'Radio and Television Broadcasting',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 1439,
        shortCode: '51',
        NAICSGroup: 'Information',
        code: '5152',
        title: 'Cable and Other Subscription Programming',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 1443,
        shortCode: '51',
        NAICSGroup: 'Information',
        code: '5173',
        title: 'Wired and Wireless Telecommunications Carriers',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 1447,
        shortCode: '51',
        NAICSGroup: 'Information',
        code: '5174',
        title: 'Satellite Telecommunications',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 1450,
        shortCode: '51',
        NAICSGroup: 'Information',
        code: '5179',
        title: 'Other Telecommunications',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 1455,
        shortCode: '51',
        NAICSGroup: 'Information',
        code: '5182',
        title: 'Data Processing, Hosting, and Related Services',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 1459,
        shortCode: '51',
        NAICSGroup: 'Information',
        code: '5191',
        title: 'Other Information Services',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 1470,
        shortCode: '52',
        NAICSGroup: 'Finance and Insurance',
        code: '5211',
        title: 'Monetary Authorities-Central Bank',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 1474,
        shortCode: '52',
        NAICSGroup: 'Finance and Insurance',
        code: '5221',
        title: 'Depository Credit Intermediation ',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 1483,
        shortCode: '52',
        NAICSGroup: 'Finance and Insurance',
        code: '5222',
        title: 'Nondepository Credit Intermediation ',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 1494,
        shortCode: '52',
        NAICSGroup: 'Finance and Insurance',
        code: '5223',
        title: 'Activities Related to Credit Intermediation ',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 1502,
        shortCode: '52',
        NAICSGroup: 'Finance and Insurance',
        code: '5231',
        title: 'Securities and Commodity Contracts Intermediation and Brokerage',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 1511,
        shortCode: '52',
        NAICSGroup: 'Finance and Insurance',
        code: '5232',
        title: 'Securities and Commodity Exchanges',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 1514,
        shortCode: '52',
        NAICSGroup: 'Finance and Insurance',
        code: '5239',
        title: 'Other Financial Investment Activities',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 1525,
        shortCode: '52',
        NAICSGroup: 'Finance and Insurance',
        code: '5241',
        title: 'Insurance Carriers',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 1535,
        shortCode: '52',
        NAICSGroup: 'Finance and Insurance',
        code: '5242',
        title: 'Agencies, Brokerages, and Other Insurance Related Activities',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 1543,
        shortCode: '52',
        NAICSGroup: 'Finance and Insurance',
        code: '5251',
        title: 'Insurance and Employee Benefit Funds ',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 1550,
        shortCode: '52',
        NAICSGroup: 'Finance and Insurance',
        code: '5259',
        title: 'Other Investment Pools and Funds',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 1559,
        shortCode: '53',
        NAICSGroup: 'Real Estate and Rental and Leasing',
        code: '5311',
        title: 'Lessors of Real Estate',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 1568,
        shortCode: '53',
        NAICSGroup: 'Real Estate and Rental and Leasing',
        code: '5312',
        title: 'Offices of Real Estate Agents and Brokers',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 1571,
        shortCode: '53',
        NAICSGroup: 'Real Estate and Rental and Leasing',
        code: '5313',
        title: 'Activities Related to Real Estate',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 1580,
        shortCode: '53',
        NAICSGroup: 'Real Estate and Rental and Leasing',
        code: '5321',
        title: 'Automotive Equipment Rental and Leasing',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 1586,
        shortCode: '53',
        NAICSGroup: 'Real Estate and Rental and Leasing',
        code: '5322',
        title: 'Consumer Goods Rental',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 1595,
        shortCode: '53',
        NAICSGroup: 'Real Estate and Rental and Leasing',
        code: '5323',
        title: 'General Rental Centers',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 1598,
        shortCode: '53',
        NAICSGroup: 'Real Estate and Rental and Leasing',
        code: '5324',
        title: 'Commercial and Industrial Machinery and Equipment Rental and Leasing',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 1607,
        shortCode: '53',
        NAICSGroup: 'Real Estate and Rental and Leasing',
        code: '5331',
        title: 'Lessors of Nonfinancial Intangible Assets (except Copyrighted Works)',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 1612,
        shortCode: '54',
        NAICSGroup: 'Professional, Scientific, and Technical Services',
        code: '5411',
        title: 'Legal Services',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 1620,
        shortCode: '54',
        NAICSGroup: 'Professional, Scientific, and Technical Services',
        code: '5412',
        title: 'Accounting, Tax Preparation, Bookkeeping, and Payroll Services',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 1626,
        shortCode: '54',
        NAICSGroup: 'Professional, Scientific, and Technical Services',
        code: '5413',
        title: 'Architectural, Engineering, and Related Services',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 1643,
        shortCode: '54',
        NAICSGroup: 'Professional, Scientific, and Technical Services',
        code: '5414',
        title: 'Specialized Design Services',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 1652,
        shortCode: '54',
        NAICSGroup: 'Professional, Scientific, and Technical Services',
        code: '5415',
        title: 'Computer Systems Design and Related Services',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 1658,
        shortCode: '54',
        NAICSGroup: 'Professional, Scientific, and Technical Services',
        code: '5416',
        title: 'Management, Scientific, and Technical Consulting Services',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 1669,
        shortCode: '54',
        NAICSGroup: 'Professional, Scientific, and Technical Services',
        code: '5417',
        title: 'Scientific Research and Development Services',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 1676,
        shortCode: '54',
        NAICSGroup: 'Professional, Scientific, and Technical Services',
        code: '5418',
        title: 'Advertising, Public Relations, and Related Services',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 1693,
        shortCode: '54',
        NAICSGroup: 'Professional, Scientific, and Technical Services',
        code: '5419',
        title: 'Other Professional, Scientific, and Technical Services',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 1707,
        shortCode: '55',
        NAICSGroup: 'Management of Companies and Enterprises',
        code: '5511',
        title: 'Management of Companies and Enterprises',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 1714,
        shortCode: '56',
        NAICSGroup: 'Administrative and Support and Waste Management and Remediation Services',
        code: '5611',
        title: 'Office Administrative Services',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 1717,
        shortCode: '56',
        NAICSGroup: 'Administrative and Support and Waste Management and Remediation Services',
        code: '5612',
        title: 'Facilities Support Services',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 1720,
        shortCode: '56',
        NAICSGroup: 'Administrative and Support and Waste Management and Remediation Services',
        code: '5613',
        title: 'Employment Services',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 1728,
        shortCode: '56',
        NAICSGroup: 'Administrative and Support and Waste Management and Remediation Services',
        code: '5614',
        title: 'Business Support Services',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 1745,
        shortCode: '56',
        NAICSGroup: 'Administrative and Support and Waste Management and Remediation Services',
        code: '5615',
        title: 'Travel Arrangement and Reservation Services',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 1753,
        shortCode: '56',
        NAICSGroup: 'Administrative and Support and Waste Management and Remediation Services',
        code: '5616',
        title: 'Investigation and Security Services',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 1761,
        shortCode: '56',
        NAICSGroup: 'Administrative and Support and Waste Management and Remediation Services',
        code: '5617',
        title: 'Services to Buildings and Dwellings',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 1772,
        shortCode: '56',
        NAICSGroup: 'Administrative and Support and Waste Management and Remediation Services',
        code: '5619',
        title: 'Other Support Services',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 1780,
        shortCode: '56',
        NAICSGroup: 'Administrative and Support and Waste Management and Remediation Services',
        code: '5621',
        title: 'Waste Collection ',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 1785,
        shortCode: '56',
        NAICSGroup: 'Administrative and Support and Waste Management and Remediation Services',
        code: '5622',
        title: 'Waste Treatment and Disposal ',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 1791,
        shortCode: '56',
        NAICSGroup: 'Administrative and Support and Waste Management and Remediation Services',
        code: '5629',
        title: 'Remediation and Other Waste Management Services ',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 1801,
        shortCode: '61',
        NAICSGroup: 'Educational Services',
        code: '6111',
        title: 'Elementary and Secondary Schools',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 1804,
        shortCode: '61',
        NAICSGroup: 'Educational Services',
        code: '6112',
        title: 'Junior Colleges',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 1807,
        shortCode: '61',
        NAICSGroup: 'Educational Services',
        code: '6113',
        title: 'Colleges, Universities, and Professional Schools',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 1810,
        shortCode: '61',
        NAICSGroup: 'Educational Services',
        code: '6114',
        title: 'Business Schools and Computer and Management Training',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 1817,
        shortCode: '61',
        NAICSGroup: 'Educational Services',
        code: '6115',
        title: 'Technical and Trade Schools ',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 1823,
        shortCode: '61',
        NAICSGroup: 'Educational Services',
        code: '6116',
        title: 'Other Schools and Instruction',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 1834,
        shortCode: '61',
        NAICSGroup: 'Educational Services',
        code: '6117',
        title: 'Educational Support Services',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 1839,
        shortCode: '62',
        NAICSGroup: 'Health Care and Social Assistance',
        code: '6211',
        title: 'Offices of Physicians',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 1843,
        shortCode: '62',
        NAICSGroup: 'Health Care and Social Assistance',
        code: '6212',
        title: 'Offices of Dentists',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 1846,
        shortCode: '62',
        NAICSGroup: 'Health Care and Social Assistance',
        code: '6213',
        title: 'Offices of Other Health Practitioners',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 1858,
        shortCode: '62',
        NAICSGroup: 'Health Care and Social Assistance',
        code: '6214',
        title: 'Outpatient Care Centers',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 1868,
        shortCode: '62',
        NAICSGroup: 'Health Care and Social Assistance',
        code: '6215',
        title: 'Medical and Diagnostic Laboratories',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 1872,
        shortCode: '62',
        NAICSGroup: 'Health Care and Social Assistance',
        code: '6216',
        title: 'Home Health Care Services',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 1875,
        shortCode: '62',
        NAICSGroup: 'Health Care and Social Assistance',
        code: '6219',
        title: 'Other Ambulatory Health Care Services',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 1882,
        shortCode: '62',
        NAICSGroup: 'Health Care and Social Assistance',
        code: '6221',
        title: 'General Medical and Surgical Hospitals',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 1885,
        shortCode: '62',
        NAICSGroup: 'Health Care and Social Assistance',
        code: '6222',
        title: 'Psychiatric and Substance Abuse Hospitals',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 1888,
        shortCode: '62',
        NAICSGroup: 'Health Care and Social Assistance',
        code: '6223',
        title: 'Specialty (except Psychiatric and Substance Abuse) Hospitals',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 1892,
        shortCode: '62',
        NAICSGroup: 'Health Care and Social Assistance',
        code: '6231',
        title: 'Nursing Care Facilities (Skilled Nursing Facilities)',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 1895,
        shortCode: '62',
        NAICSGroup: 'Health Care and Social Assistance',
        code: '6232',
        title: 'Residential Intellectual and Developmental Disability, Mental Health, and Substance Abuse Facilities',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 1900,
        shortCode: '62',
        NAICSGroup: 'Health Care and Social Assistance',
        code: '6233',
        title: 'Continuing Care Retirement Communities and Assisted Living Facilities for the Elderly',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 1904,
        shortCode: '62',
        NAICSGroup: 'Health Care and Social Assistance',
        code: '6239',
        title: 'Other Residential Care Facilities',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 1908,
        shortCode: '62',
        NAICSGroup: 'Health Care and Social Assistance',
        code: '6241',
        title: 'Individual and Family Services',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 1915,
        shortCode: '62',
        NAICSGroup: 'Health Care and Social Assistance',
        code: '6242',
        title: 'Community Food and Housing, and Emergency and Other Relief Services',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 1923,
        shortCode: '62',
        NAICSGroup: 'Health Care and Social Assistance',
        code: '6243',
        title: 'Vocational Rehabilitation Services',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 1926,
        shortCode: '62',
        NAICSGroup: 'Health Care and Social Assistance',
        code: '6244',
        title: 'Child Day Care Services',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 1931,
        shortCode: '71',
        NAICSGroup: 'Arts, Entertainment, and Recreation',
        code: '7111',
        title: 'Performing Arts Companies',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 1940,
        shortCode: '71',
        NAICSGroup: 'Arts, Entertainment, and Recreation',
        code: '7112',
        title: 'Spectator Sports',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 1945,
        shortCode: '71',
        NAICSGroup: 'Arts, Entertainment, and Recreation',
        code: '7113',
        title: 'Promoters of Performing Arts, Sports, and Similar Events',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 1950,
        shortCode: '71',
        NAICSGroup: 'Arts, Entertainment, and Recreation',
        code: '7114',
        title: 'Agents and Managers for Artists, Athletes, Entertainers, and Other Public Figures',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 1953,
        shortCode: '71',
        NAICSGroup: 'Arts, Entertainment, and Recreation',
        code: '7115',
        title: 'Independent Artists, Writers, and Performers',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 1957,
        shortCode: '71',
        NAICSGroup: 'Arts, Entertainment, and Recreation',
        code: '7121',
        title: 'Museums, Historical Sites, and Similar Institutions',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 1967,
        shortCode: '71',
        NAICSGroup: 'Arts, Entertainment, and Recreation',
        code: '7131',
        title: 'Amusement Parks and Arcades',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 1972,
        shortCode: '71',
        NAICSGroup: 'Arts, Entertainment, and Recreation',
        code: '7132',
        title: 'Gambling Industries',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 1977,
        shortCode: '71',
        NAICSGroup: 'Arts, Entertainment, and Recreation',
        code: '7139',
        title: 'Other Amusement and Recreation Industries',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 1992,
        shortCode: '72',
        NAICSGroup: 'Accommodation and Food Services',
        code: '7211',
        title: 'Traveler Accommodation',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 2000,
        shortCode: '72',
        NAICSGroup: 'Accommodation and Food Services',
        code: '7212',
        title: 'RV (Recreational Vehicle) Parks and Recreational Camps',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 2004,
        shortCode: '72',
        NAICSGroup: 'Accommodation and Food Services',
        code: '7213',
        title: "Rooming and Boarding Houses, Dormitories, and Workers' Camps",
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 2008,
        shortCode: '72',
        NAICSGroup: 'Accommodation and Food Services',
        code: '7223',
        title: 'Special Food Services',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 2015,
        shortCode: '72',
        NAICSGroup: 'Accommodation and Food Services',
        code: '7224',
        title: 'Drinking Places (Alcoholic Beverages)',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 2018,
        shortCode: '72',
        NAICSGroup: 'Accommodation and Food Services',
        code: '7225',
        title: 'Restaurants and Other Eating Places',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 2026,
        shortCode: '81',
        NAICSGroup: 'Other Services (except Public Administration)',
        code: '8111',
        title: 'Automotive Repair and Maintenance',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 2039,
        shortCode: '81',
        NAICSGroup: 'Other Services (except Public Administration)',
        code: '8112',
        title: 'Electronic and Precision Equipment Repair and Maintenance',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 2045,
        shortCode: '81',
        NAICSGroup: 'Other Services (except Public Administration)',
        code: '8113',
        title: 'Commercial and Industrial Machinery and Equipment (except Automotive and Electronic) Repair and Maintenance',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 2048,
        shortCode: '81',
        NAICSGroup: 'Other Services (except Public Administration)',
        code: '8114',
        title: 'Personal and Household Goods Repair and Maintenance',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 2059,
        shortCode: '81',
        NAICSGroup: 'Other Services (except Public Administration)',
        code: '8121',
        title: 'Personal Care Services ',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 2067,
        shortCode: '81',
        NAICSGroup: 'Other Services (except Public Administration)',
        code: '8122',
        title: 'Death Care Services ',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 2072,
        shortCode: '81',
        NAICSGroup: 'Other Services (except Public Administration)',
        code: '8123',
        title: 'Drycleaning and Laundry Services ',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 2080,
        shortCode: '81',
        NAICSGroup: 'Other Services (except Public Administration)',
        code: '8129',
        title: 'Other Personal Services ',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 2091,
        shortCode: '81',
        NAICSGroup: 'Other Services (except Public Administration)',
        code: '8131',
        title: 'Religious Organizations ',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 2094,
        shortCode: '81',
        NAICSGroup: 'Other Services (except Public Administration)',
        code: '8132',
        title: 'Grantmaking and Giving Services ',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 2099,
        shortCode: '81',
        NAICSGroup: 'Other Services (except Public Administration)',
        code: '8133',
        title: 'Social Advocacy Organizations ',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 2104,
        shortCode: '81',
        NAICSGroup: 'Other Services (except Public Administration)',
        code: '8134',
        title: 'Civic and Social Organizations ',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 2107,
        shortCode: '81',
        NAICSGroup: 'Other Services (except Public Administration)',
        code: '8139',
        title: 'Business, Professional, Labor, Political, and Similar Organizations ',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 2119,
        shortCode: '81',
        NAICSGroup: 'Other Services (except Public Administration)',
        code: '8141',
        title: 'Private Households',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 2124,
        shortCode: '92',
        NAICSGroup: 'Public Administration',
        code: '9211',
        title: 'Executive, Legislative, and Other General Government Support ',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 2138,
        shortCode: '92',
        NAICSGroup: 'Public Administration',
        code: '9221',
        title: 'Justice, Public Order, and Safety Activities ',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 2154,
        shortCode: '92',
        NAICSGroup: 'Public Administration',
        code: '9231',
        title: 'Administration of Human Resource Programs ',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 2164,
        shortCode: '92',
        NAICSGroup: 'Public Administration',
        code: '9241',
        title: 'Administration of Environmental Quality Programs ',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 2170,
        shortCode: '92',
        NAICSGroup: 'Public Administration',
        code: '9251',
        title: 'Administration of Housing Programs, Urban Planning, and Community Development ',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 2176,
        shortCode: '92',
        NAICSGroup: 'Public Administration',
        code: '9261',
        title: 'Administration of Economic Programs ',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 2188,
        shortCode: '92',
        NAICSGroup: 'Public Administration',
        code: '9271',
        title: 'Space Research and Technology ',
        year: 2017,
        status: 'Active',
    },
    {
        sequenceNo: 2192,
        shortCode: '92',
        NAICSGroup: 'Public Administration',
        code: '9281',
        title: 'National Security and International Affairs ',
        year: 2017,
        status: 'Active',
    },
];

export default NAICSCode;
